version: "2"
services:
  node:
    image: "node"
    user: "node"
    working_dir: /home/carlos/Web/myWebpage/
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/carlos/Web/myWebpage/
    ports:
      - 8080:8080
    command: "npm run build"
#    command: "npm run start"
#    command: "npm update"
#    command: "sudo npm install -g npm-check-updates"
#    command: "npm install webpack-dev-server --save-dev"
#    command: "npm install sass --save-dev"
#    command: "npm i terser@3.14 --save-dev"
#    command: "npm i --save-dev html-webpack-plugin"
#    command: "npm install style-loader css-loader sass-loader node-sass --save-dev"
#    command: "npm install node-sass --save-dev"
#    command: "npm install i18next --save-dev"
#    command: "npm i @alienfast/i18next-loader --save-dev"
#    command: npm install i18next-browser-languagedetector
#    command: "npm install --save-dev mini-css-extract-plugin"
#    command: "npm i -D webpack-merge"
#    command: "npm install --save-dev preload-webpack-plugin"
